-- Canonical skill taxonomy.
--
-- Generated and validated for uniqueness before commit: skill_alias carries a GLOBAL
-- unique index, so a single duplicate alias anywhere fails this migration and the
-- service will not start.
--
-- Aliases exist so free-text resume parsing resolves 'JS', 'ES6' and 'Javascript' to
-- the one canonical JavaScript row. resume-service builds its Aho-Corasick automaton
-- from exactly this table.

INSERT INTO skill (id, name, slug, category) VALUES
    (gen_random_uuid(), 'Java', 'java', 'Programming Languages'),
    (gen_random_uuid(), 'Python', 'python', 'Programming Languages'),
    (gen_random_uuid(), 'JavaScript', 'javascript', 'Programming Languages'),
    (gen_random_uuid(), 'TypeScript', 'typescript', 'Programming Languages'),
    (gen_random_uuid(), 'C#', 'csharp', 'Programming Languages'),
    (gen_random_uuid(), 'C++', 'cpp', 'Programming Languages'),
    (gen_random_uuid(), 'C', 'c-language', 'Programming Languages'),
    (gen_random_uuid(), 'Go', 'golang', 'Programming Languages'),
    (gen_random_uuid(), 'Rust', 'rust', 'Programming Languages'),
    (gen_random_uuid(), 'Kotlin', 'kotlin', 'Programming Languages'),
    (gen_random_uuid(), 'Swift', 'swift', 'Programming Languages'),
    (gen_random_uuid(), 'PHP', 'php', 'Programming Languages'),
    (gen_random_uuid(), 'Ruby', 'ruby', 'Programming Languages'),
    (gen_random_uuid(), 'Scala', 'scala', 'Programming Languages'),
    (gen_random_uuid(), 'R', 'r-language', 'Programming Languages'),
    (gen_random_uuid(), 'MATLAB', 'matlab', 'Programming Languages'),
    (gen_random_uuid(), 'Dart', 'dart', 'Programming Languages'),
    (gen_random_uuid(), 'Perl', 'perl', 'Programming Languages'),
    (gen_random_uuid(), 'Bash', 'bash', 'Programming Languages'),
    (gen_random_uuid(), 'PowerShell', 'powershell', 'Programming Languages'),
    (gen_random_uuid(), 'SQL', 'sql', 'Programming Languages'),
    (gen_random_uuid(), 'React', 'react', 'Frontend'),
    (gen_random_uuid(), 'Next.js', 'nextjs', 'Frontend'),
    (gen_random_uuid(), 'Vue.js', 'vuejs', 'Frontend'),
    (gen_random_uuid(), 'Angular', 'angular', 'Frontend'),
    (gen_random_uuid(), 'Svelte', 'svelte', 'Frontend'),
    (gen_random_uuid(), 'HTML', 'html', 'Frontend'),
    (gen_random_uuid(), 'CSS', 'css', 'Frontend'),
    (gen_random_uuid(), 'Sass', 'sass', 'Frontend'),
    (gen_random_uuid(), 'Tailwind CSS', 'tailwind-css', 'Frontend'),
    (gen_random_uuid(), 'Bootstrap', 'bootstrap', 'Frontend'),
    (gen_random_uuid(), 'Redux', 'redux', 'Frontend'),
    (gen_random_uuid(), 'Webpack', 'webpack', 'Frontend'),
    (gen_random_uuid(), 'Vite', 'vite', 'Frontend'),
    (gen_random_uuid(), 'jQuery', 'jquery', 'Frontend'),
    (gen_random_uuid(), 'Material UI', 'material-ui', 'Frontend'),
    (gen_random_uuid(), 'Responsive Design', 'responsive-design', 'Frontend'),
    (gen_random_uuid(), 'Web Accessibility', 'web-accessibility', 'Frontend'),
    (gen_random_uuid(), 'Spring Boot', 'spring-boot', 'Backend'),
    (gen_random_uuid(), 'Spring Framework', 'spring-framework', 'Backend'),
    (gen_random_uuid(), 'Spring Security', 'spring-security', 'Backend'),
    (gen_random_uuid(), 'Spring Cloud', 'spring-cloud', 'Backend'),
    (gen_random_uuid(), 'Hibernate', 'hibernate', 'Backend'),
    (gen_random_uuid(), 'Node.js', 'nodejs', 'Backend'),
    (gen_random_uuid(), 'Express.js', 'expressjs', 'Backend'),
    (gen_random_uuid(), 'NestJS', 'nestjs', 'Backend'),
    (gen_random_uuid(), 'Django', 'django', 'Backend'),
    (gen_random_uuid(), 'Flask', 'flask', 'Backend'),
    (gen_random_uuid(), 'FastAPI', 'fastapi', 'Backend'),
    (gen_random_uuid(), 'ASP.NET Core', 'aspnet-core', 'Backend'),
    (gen_random_uuid(), 'Laravel', 'laravel', 'Backend'),
    (gen_random_uuid(), 'Ruby on Rails', 'ruby-on-rails', 'Backend'),
    (gen_random_uuid(), 'REST API', 'rest-api', 'Backend'),
    (gen_random_uuid(), 'GraphQL', 'graphql', 'Backend'),
    (gen_random_uuid(), 'gRPC', 'grpc', 'Backend'),
    (gen_random_uuid(), 'Microservices', 'microservices', 'Backend'),
    (gen_random_uuid(), 'WebSockets', 'websockets', 'Backend'),
    (gen_random_uuid(), 'Apache Kafka', 'kafka', 'Backend'),
    (gen_random_uuid(), 'RabbitMQ', 'rabbitmq', 'Backend'),
    (gen_random_uuid(), 'Redis', 'redis', 'Backend'),
    (gen_random_uuid(), 'Elasticsearch', 'elasticsearch', 'Backend'),
    (gen_random_uuid(), 'OAuth 2.0', 'oauth2', 'Backend'),
    (gen_random_uuid(), 'JWT', 'jwt', 'Backend'),
    (gen_random_uuid(), 'PostgreSQL', 'postgresql', 'Databases'),
    (gen_random_uuid(), 'MySQL', 'mysql', 'Databases'),
    (gen_random_uuid(), 'MongoDB', 'mongodb', 'Databases'),
    (gen_random_uuid(), 'SQLite', 'sqlite', 'Databases'),
    (gen_random_uuid(), 'Oracle Database', 'oracle-database', 'Databases'),
    (gen_random_uuid(), 'Microsoft SQL Server', 'sql-server', 'Databases'),
    (gen_random_uuid(), 'Cassandra', 'cassandra', 'Databases'),
    (gen_random_uuid(), 'DynamoDB', 'dynamodb', 'Databases'),
    (gen_random_uuid(), 'Neo4j', 'neo4j', 'Databases'),
    (gen_random_uuid(), 'Database Design', 'database-design', 'Databases'),
    (gen_random_uuid(), 'Query Optimization', 'query-optimization', 'Databases'),
    (gen_random_uuid(), 'Docker', 'docker', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Kubernetes', 'kubernetes', 'Cloud & DevOps'),
    (gen_random_uuid(), 'AWS', 'aws', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Microsoft Azure', 'azure', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Google Cloud Platform', 'gcp', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Terraform', 'terraform', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Ansible', 'ansible', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Jenkins', 'jenkins', 'Cloud & DevOps'),
    (gen_random_uuid(), 'GitHub Actions', 'github-actions', 'Cloud & DevOps'),
    (gen_random_uuid(), 'GitLab CI', 'gitlab-ci', 'Cloud & DevOps'),
    (gen_random_uuid(), 'CI/CD', 'ci-cd', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Nginx', 'nginx', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Apache HTTP Server', 'apache-http-server', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Linux', 'linux', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Prometheus', 'prometheus', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Grafana', 'grafana', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Serverless', 'serverless', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Load Balancing', 'load-balancing', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Site Reliability Engineering', 'sre', 'Cloud & DevOps'),
    (gen_random_uuid(), 'Machine Learning', 'machine-learning', 'Data & ML'),
    (gen_random_uuid(), 'Deep Learning', 'deep-learning', 'Data & ML'),
    (gen_random_uuid(), 'TensorFlow', 'tensorflow', 'Data & ML'),
    (gen_random_uuid(), 'PyTorch', 'pytorch', 'Data & ML'),
    (gen_random_uuid(), 'scikit-learn', 'scikit-learn', 'Data & ML'),
    (gen_random_uuid(), 'Pandas', 'pandas', 'Data & ML'),
    (gen_random_uuid(), 'NumPy', 'numpy', 'Data & ML'),
    (gen_random_uuid(), 'Natural Language Processing', 'nlp', 'Data & ML'),
    (gen_random_uuid(), 'Computer Vision', 'computer-vision', 'Data & ML'),
    (gen_random_uuid(), 'Data Analysis', 'data-analysis', 'Data & ML'),
    (gen_random_uuid(), 'Data Visualization', 'data-visualization', 'Data & ML'),
    (gen_random_uuid(), 'Apache Spark', 'spark', 'Data & ML'),
    (gen_random_uuid(), 'Hadoop', 'hadoop', 'Data & ML'),
    (gen_random_uuid(), 'ETL', 'etl', 'Data & ML'),
    (gen_random_uuid(), 'Power BI', 'power-bi', 'Data & ML'),
    (gen_random_uuid(), 'Tableau', 'tableau', 'Data & ML'),
    (gen_random_uuid(), 'Statistics', 'statistics', 'Data & ML'),
    (gen_random_uuid(), 'Android Development', 'android', 'Mobile'),
    (gen_random_uuid(), 'iOS Development', 'ios', 'Mobile'),
    (gen_random_uuid(), 'React Native', 'react-native', 'Mobile'),
    (gen_random_uuid(), 'Flutter', 'flutter', 'Mobile'),
    (gen_random_uuid(), 'JUnit', 'junit', 'Testing'),
    (gen_random_uuid(), 'Mockito', 'mockito', 'Testing'),
    (gen_random_uuid(), 'Jest', 'jest', 'Testing'),
    (gen_random_uuid(), 'Cypress', 'cypress', 'Testing'),
    (gen_random_uuid(), 'Selenium', 'selenium', 'Testing'),
    (gen_random_uuid(), 'Playwright', 'playwright', 'Testing'),
    (gen_random_uuid(), 'PyTest', 'pytest', 'Testing'),
    (gen_random_uuid(), 'Testcontainers', 'testcontainers', 'Testing'),
    (gen_random_uuid(), 'Unit Testing', 'unit-testing', 'Testing'),
    (gen_random_uuid(), 'Integration Testing', 'integration-testing', 'Testing'),
    (gen_random_uuid(), 'Performance Testing', 'performance-testing', 'Testing'),
    (gen_random_uuid(), 'Application Security', 'application-security', 'Security'),
    (gen_random_uuid(), 'Penetration Testing', 'penetration-testing', 'Security'),
    (gen_random_uuid(), 'Cryptography', 'cryptography', 'Security'),
    (gen_random_uuid(), 'Network Security', 'network-security', 'Security'),
    (gen_random_uuid(), 'Identity and Access Management', 'iam', 'Security'),
    (gen_random_uuid(), 'Secure Coding', 'secure-coding', 'Security'),
    (gen_random_uuid(), 'Git', 'git', 'Tools & Practices'),
    (gen_random_uuid(), 'Agile', 'agile', 'Tools & Practices'),
    (gen_random_uuid(), 'Jira', 'jira', 'Tools & Practices'),
    (gen_random_uuid(), 'System Design', 'system-design', 'Tools & Practices'),
    (gen_random_uuid(), 'Design Patterns', 'design-patterns', 'Tools & Practices'),
    (gen_random_uuid(), 'Data Structures', 'data-structures', 'Tools & Practices'),
    (gen_random_uuid(), 'Object-Oriented Programming', 'oop', 'Tools & Practices'),
    (gen_random_uuid(), 'Functional Programming', 'functional-programming', 'Tools & Practices'),
    (gen_random_uuid(), 'Code Review', 'code-review', 'Tools & Practices'),
    (gen_random_uuid(), 'Technical Writing', 'technical-writing', 'Tools & Practices'),
    (gen_random_uuid(), 'Maven', 'maven', 'Tools & Practices'),
    (gen_random_uuid(), 'Gradle', 'gradle', 'Tools & Practices'),
    (gen_random_uuid(), 'npm', 'npm', 'Tools & Practices'),
    (gen_random_uuid(), 'Postman', 'postman', 'Tools & Practices'),
    (gen_random_uuid(), 'Figma', 'figma', 'Tools & Practices'),
    (gen_random_uuid(), 'Problem Solving', 'problem-solving', 'Tools & Practices'),
    (gen_random_uuid(), 'Team Leadership', 'team-leadership', 'Tools & Practices'),
    (gen_random_uuid(), 'Communication', 'communication', 'Tools & Practices');

INSERT INTO skill_alias (skill_id, alias)
SELECT s.id, a.alias
FROM skill s
JOIN (VALUES
    ('java', 'java8'),
    ('java', 'java11'),
    ('java', 'java17'),
    ('java', 'java21'),
    ('java', 'core java'),
    ('python', 'python3'),
    ('python', 'py'),
    ('javascript', 'js'),
    ('javascript', 'ecmascript'),
    ('javascript', 'es6'),
    ('javascript', 'es2015'),
    ('typescript', 'ts'),
    ('csharp', 'c sharp'),
    ('csharp', 'c#'),
    ('cpp', 'c plus plus'),
    ('cpp', 'c++'),
    ('c-language', 'ansi c'),
    ('golang', 'go lang'),
    ('golang', 'go-lang'),
    ('r-language', 'r lang'),
    ('bash', 'shell scripting'),
    ('bash', 'shell script'),
    ('bash', 'sh scripting'),
    ('powershell', 'pwsh'),
    ('sql', 'structured query language'),
    ('react', 'reactjs'),
    ('react', 'react.js'),
    ('nextjs', 'next js'),
    ('vuejs', 'vue'),
    ('vuejs', 'vue3'),
    ('angular', 'angularjs'),
    ('angular', 'angular2'),
    ('svelte', 'sveltekit'),
    ('html', 'html5'),
    ('css', 'css3'),
    ('sass', 'scss'),
    ('tailwind-css', 'tailwind'),
    ('tailwind-css', 'tailwindcss'),
    ('redux', 'redux toolkit'),
    ('material-ui', 'mui'),
    ('responsive-design', 'mobile-first design'),
    ('web-accessibility', 'a11y'),
    ('web-accessibility', 'wcag'),
    ('spring-boot', 'springboot'),
    ('spring-framework', 'spring'),
    ('spring-framework', 'spring mvc'),
    ('hibernate', 'jpa'),
    ('hibernate', 'java persistence api'),
    ('nodejs', 'node'),
    ('nodejs', 'node js'),
    ('expressjs', 'express'),
    ('nestjs', 'nest js'),
    ('fastapi', 'fast api'),
    ('aspnet-core', 'asp.net'),
    ('aspnet-core', 'aspnet'),
    ('aspnet-core', 'dotnet core'),
    ('aspnet-core', '.net core'),
    ('ruby-on-rails', 'rails'),
    ('rest-api', 'restful'),
    ('rest-api', 'rest'),
    ('rest-api', 'restful api'),
    ('microservices', 'microservice architecture'),
    ('websockets', 'websocket'),
    ('kafka', 'apache-kafka'),
    ('rabbitmq', 'rabbit mq'),
    ('elasticsearch', 'elastic search'),
    ('elasticsearch', 'opensearch'),
    ('oauth2', 'oauth'),
    ('oauth2', 'oauth 2'),
    ('jwt', 'json web token'),
    ('postgresql', 'postgres'),
    ('postgresql', 'psql'),
    ('mongodb', 'mongo'),
    ('oracle-database', 'oracle db'),
    ('oracle-database', 'plsql'),
    ('oracle-database', 'pl/sql'),
    ('sql-server', 'mssql'),
    ('sql-server', 't-sql'),
    ('sql-server', 'tsql'),
    ('cassandra', 'apache cassandra'),
    ('dynamodb', 'dynamo db'),
    ('neo4j', 'graph database'),
    ('database-design', 'schema design'),
    ('database-design', 'data modeling'),
    ('database-design', 'normalization'),
    ('query-optimization', 'sql tuning'),
    ('query-optimization', 'index tuning'),
    ('docker', 'containerization'),
    ('docker', 'containers'),
    ('kubernetes', 'k8s'),
    ('aws', 'amazon web services'),
    ('azure', 'ms azure'),
    ('gcp', 'google cloud'),
    ('terraform', 'infrastructure as code'),
    ('terraform', 'iac'),
    ('github-actions', 'gh actions'),
    ('gitlab-ci', 'gitlab ci/cd'),
    ('ci-cd', 'continuous integration'),
    ('ci-cd', 'continuous delivery'),
    ('ci-cd', 'continuous deployment'),
    ('apache-http-server', 'apache2'),
    ('apache-http-server', 'httpd'),
    ('linux', 'unix'),
    ('linux', 'ubuntu'),
    ('linux', 'debian'),
    ('linux', 'centos'),
    ('serverless', 'aws lambda'),
    ('serverless', 'lambda functions'),
    ('load-balancing', 'reverse proxy'),
    ('sre', 'observability'),
    ('sre', 'distributed tracing'),
    ('machine-learning', 'ml'),
    ('deep-learning', 'neural networks'),
    ('tensorflow', 'tensor flow'),
    ('pytorch', 'torch'),
    ('scikit-learn', 'sklearn'),
    ('scikit-learn', 'scikit learn'),
    ('nlp', 'natural language processing'),
    ('computer-vision', 'opencv'),
    ('computer-vision', 'image processing'),
    ('data-analysis', 'data analytics'),
    ('data-analysis', 'exploratory data analysis'),
    ('data-visualization', 'matplotlib'),
    ('data-visualization', 'seaborn'),
    ('spark', 'pyspark'),
    ('spark', 'apache-spark'),
    ('hadoop', 'mapreduce'),
    ('etl', 'data pipeline'),
    ('etl', 'elt'),
    ('power-bi', 'powerbi'),
    ('statistics', 'statistical analysis'),
    ('android', 'android sdk'),
    ('android', 'jetpack compose'),
    ('ios', 'swiftui'),
    ('ios', 'uikit'),
    ('junit', 'junit5'),
    ('selenium', 'webdriver'),
    ('unit-testing', 'tdd'),
    ('unit-testing', 'test driven development'),
    ('integration-testing', 'e2e testing'),
    ('integration-testing', 'end-to-end testing'),
    ('performance-testing', 'load testing'),
    ('performance-testing', 'jmeter'),
    ('performance-testing', 'k6'),
    ('application-security', 'appsec'),
    ('application-security', 'owasp'),
    ('penetration-testing', 'pentesting'),
    ('penetration-testing', 'ethical hacking'),
    ('cryptography', 'encryption'),
    ('cryptography', 'tls'),
    ('cryptography', 'ssl'),
    ('network-security', 'firewall'),
    ('network-security', 'vpn'),
    ('iam', 'sso'),
    ('iam', 'single sign-on'),
    ('iam', 'rbac'),
    ('secure-coding', 'threat modeling'),
    ('secure-coding', 'sast'),
    ('git', 'version control'),
    ('git', 'github'),
    ('git', 'gitlab'),
    ('git', 'bitbucket'),
    ('agile', 'scrum'),
    ('agile', 'kanban'),
    ('agile', 'sprint planning'),
    ('jira', 'atlassian jira'),
    ('system-design', 'software architecture'),
    ('system-design', 'architectural design'),
    ('design-patterns', 'gof patterns'),
    ('design-patterns', 'solid principles'),
    ('data-structures', 'algorithms'),
    ('data-structures', 'dsa'),
    ('oop', 'object oriented programming'),
    ('oop', 'object-oriented design'),
    ('code-review', 'peer review'),
    ('technical-writing', 'documentation'),
    ('maven', 'apache maven'),
    ('npm', 'yarn'),
    ('npm', 'pnpm'),
    ('postman', 'api testing'),
    ('figma', 'ui design'),
    ('figma', 'ux design'),
    ('problem-solving', 'analytical thinking'),
    ('team-leadership', 'mentoring'),
    ('team-leadership', 'technical leadership'),
    ('communication', 'stakeholder management')
) AS a(slug, alias) ON a.slug = s.slug;
