-- Free-course catalog for the skill-gap feature.
--
-- Every skill_slug below is validated at generation time against profile-service's
-- V2__seed_skills.sql taxonomy. That check matters because a typo'd slug fails
-- SILENTLY at runtime: the gap is still reported, it just recommends nothing, with
-- no error anywhere to notice.
--
-- Curated toward genuinely free or audit-able resources (official docs, freeCodeCamp,
-- vendor learning portals). Not exhaustive by design -- a skill with no row here
-- simply gets no recommendation, which beats inventing a plausible-looking dead link.

INSERT INTO course (id, skill_slug, provider, title, url) VALUES
    (gen_random_uuid(), 'java', 'freeCodeCamp', 'Java Programming for Beginners (full course)', 'https://www.youtube.com/watch?v=A74TOX803D0'),
    (gen_random_uuid(), 'python', 'freeCodeCamp', 'Python for Everybody (full course)', 'https://www.youtube.com/watch?v=8DvywoWv6fI'),
    (gen_random_uuid(), 'javascript', 'freeCodeCamp', 'JavaScript Algorithms and Data Structures', 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/'),
    (gen_random_uuid(), 'typescript', 'freeCodeCamp', 'TypeScript Full Course for Beginners', 'https://www.youtube.com/watch?v=30LWjhZzg50'),
    (gen_random_uuid(), 'golang', 'freeCodeCamp', 'Learn Go Programming (full course)', 'https://www.youtube.com/watch?v=YS4e4q9oBaU'),
    (gen_random_uuid(), 'csharp', 'freeCodeCamp', 'C# Tutorial - Full Course for Beginners', 'https://www.youtube.com/watch?v=GhQdlIFylQ8'),
    (gen_random_uuid(), 'cpp', 'freeCodeCamp', 'C++ Tutorial for Beginners (full course)', 'https://www.youtube.com/watch?v=vLnPwxZdW4Y'),
    (gen_random_uuid(), 'kotlin', 'freeCodeCamp', 'Kotlin Course - Tutorial for Beginners', 'https://www.youtube.com/watch?v=F9UC9DY-vIU'),
    (gen_random_uuid(), 'rust', 'freeCodeCamp', 'Rust Programming Course for Beginners', 'https://www.youtube.com/watch?v=MsocPEZBd-M'),
    (gen_random_uuid(), 'php', 'freeCodeCamp', 'PHP Programming Language Tutorial', 'https://www.youtube.com/watch?v=OK_JCtrrv-c'),
    (gen_random_uuid(), 'ruby', 'freeCodeCamp', 'Ruby Programming Language - Full Course', 'https://www.youtube.com/watch?v=t_ispmWmdjY'),
    (gen_random_uuid(), 'swift', 'freeCodeCamp', 'Swift Programming Tutorial for Beginners', 'https://www.youtube.com/watch?v=comQ1-x2a1Q'),
    (gen_random_uuid(), 'scala', 'Coursera (audit)', 'Functional Programming Principles in Scala', 'https://www.coursera.org/learn/scala-functional-programming'),
    (gen_random_uuid(), 'sql', 'freeCodeCamp', 'SQL Tutorial - Full Database Course for Beginners', 'https://www.youtube.com/watch?v=HXV3zeQKqGY'),
    (gen_random_uuid(), 'bash', 'freeCodeCamp', 'Bash Scripting Full Course', 'https://www.youtube.com/watch?v=tK9Oc6AEnR4'),
    (gen_random_uuid(), 'r-language', 'freeCodeCamp', 'R Programming Tutorial - Full Course', 'https://www.youtube.com/watch?v=_V8eKsto3Ug'),
    (gen_random_uuid(), 'react', 'freeCodeCamp', 'Front End Development Libraries (React)', 'https://www.freecodecamp.org/learn/front-end-development-libraries/'),
    (gen_random_uuid(), 'angular', 'freeCodeCamp', 'Angular for Beginners - Full Course', 'https://www.youtube.com/watch?v=3qBXWUpoPHo'),
    (gen_random_uuid(), 'vuejs', 'freeCodeCamp', 'Vue.js Course for Beginners', 'https://www.youtube.com/watch?v=FXpIoQ_rT_c'),
    (gen_random_uuid(), 'nextjs', 'freeCodeCamp', 'Next.js Full Course for Beginners', 'https://www.youtube.com/watch?v=Zq5fmkH0T78'),
    (gen_random_uuid(), 'html', 'freeCodeCamp', 'Responsive Web Design (HTML)', 'https://www.freecodecamp.org/learn/2022/responsive-web-design/'),
    (gen_random_uuid(), 'css', 'freeCodeCamp', 'Responsive Web Design (CSS)', 'https://www.freecodecamp.org/learn/2022/responsive-web-design/'),
    (gen_random_uuid(), 'tailwind-css', 'freeCodeCamp', 'Tailwind CSS Full Course', 'https://www.youtube.com/watch?v=lCxcTsOHrjo'),
    (gen_random_uuid(), 'sass', 'freeCodeCamp', 'Sass Tutorial - Full Course', 'https://www.youtube.com/watch?v=_a5j7KoflTs'),
    (gen_random_uuid(), 'redux', 'freeCodeCamp', 'Redux Toolkit Complete Tutorial', 'https://www.youtube.com/watch?v=bbkBuqC1rU4'),
    (gen_random_uuid(), 'svelte', 'freeCodeCamp', 'Svelte Full Course for Beginners', 'https://www.youtube.com/watch?v=UGBJHYpHPvA'),
    (gen_random_uuid(), 'webpack', 'freeCodeCamp', 'Webpack Full Tutorial', 'https://www.youtube.com/watch?v=MpGLUVbqoYQ'),
    (gen_random_uuid(), 'web-accessibility', 'web.dev', 'Learn Accessibility', 'https://web.dev/learn/accessibility/'),
    (gen_random_uuid(), 'responsive-design', 'web.dev', 'Learn Responsive Design', 'https://web.dev/learn/design/'),
    (gen_random_uuid(), 'spring-boot', 'freeCodeCamp', 'Spring Boot Full Course', 'https://www.youtube.com/watch?v=9SGDpanrc8U'),
    (gen_random_uuid(), 'spring-framework', 'Spring.io', 'Official Spring Guides', 'https://spring.io/guides'),
    (gen_random_uuid(), 'spring-security', 'Spring.io', 'Spring Security Reference Documentation', 'https://docs.spring.io/spring-security/reference/'),
    (gen_random_uuid(), 'nodejs', 'freeCodeCamp', 'Node.js and Express.js Full Course', 'https://www.youtube.com/watch?v=Oe421EPjeBE'),
    (gen_random_uuid(), 'expressjs', 'freeCodeCamp', 'Back End Development and APIs (Express)', 'https://www.freecodecamp.org/learn/back-end-development-and-apis/'),
    (gen_random_uuid(), 'django', 'freeCodeCamp', 'Django Full Course for Beginners', 'https://www.youtube.com/watch?v=rHux0gMZ3Eg'),
    (gen_random_uuid(), 'flask', 'freeCodeCamp', 'Flask Course - Python Web Development', 'https://www.youtube.com/watch?v=Qr4QMBUPxWo'),
    (gen_random_uuid(), 'fastapi', 'freeCodeCamp', 'FastAPI Course for Beginners', 'https://www.youtube.com/watch?v=tLKKmouUams'),
    (gen_random_uuid(), 'laravel', 'Laravel', 'Official Laravel Documentation', 'https://laravel.com/docs'),
    (gen_random_uuid(), 'rest-api', 'freeCodeCamp', 'REST API Design Best Practices', 'https://www.freecodecamp.org/news/rest-api-design-best-practices-build-a-rest-api/'),
    (gen_random_uuid(), 'graphql', 'freeCodeCamp', 'GraphQL Full Course', 'https://www.youtube.com/watch?v=ed8SzALpx1Q'),
    (gen_random_uuid(), 'microservices', 'freeCodeCamp', 'Microservices Architecture Course', 'https://www.youtube.com/watch?v=DzGWa18NrnM'),
    (gen_random_uuid(), 'kafka', 'Confluent Developer', 'Apache Kafka 101 (free course)', 'https://developer.confluent.io/courses/apache-kafka/events/'),
    (gen_random_uuid(), 'rabbitmq', 'CloudAMQP', 'RabbitMQ for Beginners', 'https://www.cloudamqp.com/blog/part1-rabbitmq-for-beginners-what-is-rabbitmq.html'),
    (gen_random_uuid(), 'redis', 'Redis University', 'RU101: Introduction to Redis Data Structures', 'https://university.redis.io/'),
    (gen_random_uuid(), 'elasticsearch', 'Elastic', 'Elasticsearch Getting Started Guide', 'https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html'),
    (gen_random_uuid(), 'jwt', 'jwt.io', 'Introduction to JSON Web Tokens', 'https://jwt.io/introduction'),
    (gen_random_uuid(), 'oauth2', 'OAuth.net', 'OAuth 2.0 Simplified', 'https://www.oauth.com/'),
    (gen_random_uuid(), 'hibernate', 'Baeldung', 'Hibernate and JPA Tutorial Series', 'https://www.baeldung.com/learn-jpa-hibernate'),
    (gen_random_uuid(), 'websockets', 'MDN', 'WebSockets API Guide', 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API'),
    (gen_random_uuid(), 'postgresql', 'freeCodeCamp', 'PostgreSQL Full Course for Beginners', 'https://www.youtube.com/watch?v=qw--VYLpxG4'),
    (gen_random_uuid(), 'mysql', 'freeCodeCamp', 'MySQL Full Course for Beginners', 'https://www.youtube.com/watch?v=5OdVJbNCSso'),
    (gen_random_uuid(), 'mongodb', 'MongoDB University', 'Introduction to MongoDB (free)', 'https://learn.mongodb.com/'),
    (gen_random_uuid(), 'database-design', 'freeCodeCamp', 'Database Design Full Course', 'https://www.youtube.com/watch?v=ztHopE5Wnpc'),
    (gen_random_uuid(), 'query-optimization', 'Use The Index, Luke', 'SQL Indexing and Tuning Guide', 'https://use-the-index-luke.com/'),
    (gen_random_uuid(), 'sqlite', 'SQLite', 'Official SQLite Documentation', 'https://www.sqlite.org/docs.html'),
    (gen_random_uuid(), 'cassandra', 'DataStax Academy', 'Apache Cassandra Fundamentals', 'https://www.datastax.com/learn'),
    (gen_random_uuid(), 'dynamodb', 'AWS', 'Amazon DynamoDB Developer Guide', 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/'),
    (gen_random_uuid(), 'neo4j', 'Neo4j GraphAcademy', 'Neo4j Fundamentals (free)', 'https://graphacademy.neo4j.com/'),
    (gen_random_uuid(), 'docker', 'freeCodeCamp', 'Docker Tutorial for Beginners', 'https://www.youtube.com/watch?v=fqMOX6JJhGo'),
    (gen_random_uuid(), 'kubernetes', 'freeCodeCamp', 'Kubernetes Course - Full Beginners Tutorial', 'https://www.youtube.com/watch?v=d6WC5n9G_sM'),
    (gen_random_uuid(), 'aws', 'AWS Skill Builder', 'AWS Cloud Practitioner Essentials (free)', 'https://explore.skillbuilder.aws/'),
    (gen_random_uuid(), 'azure', 'Microsoft Learn', 'Azure Fundamentals Learning Path (free)', 'https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/'),
    (gen_random_uuid(), 'gcp', 'Google Cloud Skills Boost', 'Google Cloud Fundamentals', 'https://www.cloudskillsboost.google/'),
    (gen_random_uuid(), 'terraform', 'HashiCorp Developer', 'Terraform Get Started Tutorials', 'https://developer.hashicorp.com/terraform/tutorials'),
    (gen_random_uuid(), 'ansible', 'Red Hat', 'Ansible Getting Started Guide', 'https://docs.ansible.com/ansible/latest/getting_started/index.html'),
    (gen_random_uuid(), 'jenkins', 'Jenkins', 'Jenkins Official Tutorials', 'https://www.jenkins.io/doc/tutorials/'),
    (gen_random_uuid(), 'github-actions', 'GitHub Docs', 'GitHub Actions Learning Path', 'https://docs.github.com/en/actions/learn-github-actions'),
    (gen_random_uuid(), 'ci-cd', 'freeCodeCamp', 'CI/CD Pipeline Full Course', 'https://www.youtube.com/watch?v=R8_veQiYBjI'),
    (gen_random_uuid(), 'linux', 'freeCodeCamp', 'Linux Command Line Full Course', 'https://www.youtube.com/watch?v=ZtqBQ68cfJc'),
    (gen_random_uuid(), 'nginx', 'freeCodeCamp', 'NGINX Tutorial for Beginners', 'https://www.youtube.com/watch?v=7VAI73roXaY'),
    (gen_random_uuid(), 'prometheus', 'Prometheus', 'Prometheus Getting Started', 'https://prometheus.io/docs/prometheus/latest/getting_started/'),
    (gen_random_uuid(), 'grafana', 'Grafana Labs', 'Grafana Fundamentals Tutorial', 'https://grafana.com/tutorials/grafana-fundamentals/'),
    (gen_random_uuid(), 'serverless', 'AWS', 'AWS Lambda Developer Guide', 'https://docs.aws.amazon.com/lambda/latest/dg/welcome.html'),
    (gen_random_uuid(), 'sre', 'Google', 'Site Reliability Engineering Book (free online)', 'https://sre.google/books/'),
    (gen_random_uuid(), 'machine-learning', 'Coursera (audit)', 'Machine Learning Specialization - Andrew Ng', 'https://www.coursera.org/specializations/machine-learning-introduction'),
    (gen_random_uuid(), 'deep-learning', 'fast.ai', 'Practical Deep Learning for Coders', 'https://course.fast.ai/'),
    (gen_random_uuid(), 'tensorflow', 'TensorFlow', 'TensorFlow Official Tutorials', 'https://www.tensorflow.org/tutorials'),
    (gen_random_uuid(), 'pytorch', 'PyTorch', 'Learn the Basics - Official Tutorial', 'https://pytorch.org/tutorials/beginner/basics/intro.html'),
    (gen_random_uuid(), 'scikit-learn', 'scikit-learn', 'Official User Guide and Tutorials', 'https://scikit-learn.org/stable/user_guide.html'),
    (gen_random_uuid(), 'pandas', 'freeCodeCamp', 'Pandas Full Course - Data Analysis', 'https://www.youtube.com/watch?v=gtjxAH8uaP0'),
    (gen_random_uuid(), 'numpy', 'freeCodeCamp', 'NumPy Full Course for Beginners', 'https://www.youtube.com/watch?v=QUT1VHiLmmI'),
    (gen_random_uuid(), 'nlp', 'Hugging Face', 'NLP Course (free)', 'https://huggingface.co/learn/nlp-course'),
    (gen_random_uuid(), 'computer-vision', 'OpenCV', 'OpenCV Python Tutorials', 'https://docs.opencv.org/master/d6/d00/tutorial_py_root.html'),
    (gen_random_uuid(), 'data-analysis', 'freeCodeCamp', 'Data Analysis with Python (certification)', 'https://www.freecodecamp.org/learn/data-analysis-with-python/'),
    (gen_random_uuid(), 'data-visualization', 'freeCodeCamp', 'Data Visualization (certification)', 'https://www.freecodecamp.org/learn/data-visualization/'),
    (gen_random_uuid(), 'spark', 'Apache Spark', 'Spark Quick Start Guide', 'https://spark.apache.org/docs/latest/quick-start.html'),
    (gen_random_uuid(), 'statistics', 'Khan Academy', 'Statistics and Probability (free)', 'https://www.khanacademy.org/math/statistics-probability'),
    (gen_random_uuid(), 'power-bi', 'Microsoft Learn', 'Power BI Learning Paths (free)', 'https://learn.microsoft.com/en-us/training/powerplatform/power-bi'),
    (gen_random_uuid(), 'tableau', 'Tableau', 'Free Training Videos', 'https://www.tableau.com/learn/training/'),
    (gen_random_uuid(), 'android', 'Android Developers', 'Android Basics with Compose (free)', 'https://developer.android.com/courses/android-basics-compose/course'),
    (gen_random_uuid(), 'ios', 'Apple', 'SwiftUI Tutorials', 'https://developer.apple.com/tutorials/swiftui'),
    (gen_random_uuid(), 'flutter', 'Flutter', 'Official Flutter Codelabs', 'https://docs.flutter.dev/codelabs'),
    (gen_random_uuid(), 'react-native', 'React Native', 'Official Getting Started Guide', 'https://reactnative.dev/docs/getting-started'),
    (gen_random_uuid(), 'junit', 'Baeldung', 'JUnit 5 Tutorial Series', 'https://www.baeldung.com/junit-5'),
    (gen_random_uuid(), 'mockito', 'Baeldung', 'Mockito Tutorial Series', 'https://www.baeldung.com/mockito-series'),
    (gen_random_uuid(), 'jest', 'Jest', 'Official Jest Getting Started', 'https://jestjs.io/docs/getting-started'),
    (gen_random_uuid(), 'cypress', 'Cypress', 'Official Cypress Documentation', 'https://docs.cypress.io/guides/overview/why-cypress'),
    (gen_random_uuid(), 'selenium', 'Selenium', 'Selenium WebDriver Documentation', 'https://www.selenium.dev/documentation/webdriver/'),
    (gen_random_uuid(), 'playwright', 'Playwright', 'Official Playwright Getting Started', 'https://playwright.dev/docs/intro'),
    (gen_random_uuid(), 'pytest', 'pytest', 'Official pytest Documentation', 'https://docs.pytest.org/en/stable/getting-started.html'),
    (gen_random_uuid(), 'testcontainers', 'Testcontainers', 'Official Getting Started Guide', 'https://testcontainers.com/getting-started/'),
    (gen_random_uuid(), 'unit-testing', 'Martin Fowler', 'Unit Test and Test Pyramid Articles', 'https://martinfowler.com/bliki/UnitTest.html'),
    (gen_random_uuid(), 'integration-testing', 'Martin Fowler', 'Practical Test Pyramid', 'https://martinfowler.com/articles/practical-test-pyramid.html'),
    (gen_random_uuid(), 'performance-testing', 'Grafana k6', 'k6 Official Documentation', 'https://grafana.com/docs/k6/latest/'),
    (gen_random_uuid(), 'application-security', 'OWASP', 'OWASP Top 10', 'https://owasp.org/www-project-top-ten/'),
    (gen_random_uuid(), 'secure-coding', 'OWASP', 'Secure Coding Practices Quick Reference', 'https://owasp.org/www-project-secure-coding-practices-quick-reference-guide/'),
    (gen_random_uuid(), 'cryptography', 'Coursera (audit)', 'Cryptography I - Stanford', 'https://www.coursera.org/learn/crypto'),
    (gen_random_uuid(), 'penetration-testing', 'TryHackMe', 'Free Learning Paths', 'https://tryhackme.com/'),
    (gen_random_uuid(), 'network-security', 'Cisco Networking Academy', 'Introduction to Cybersecurity (free)', 'https://skillsforall.com/'),
    (gen_random_uuid(), 'iam', 'Auth0', 'Identity and Access Management Docs', 'https://auth0.com/docs/get-started/identity-fundamentals'),
    (gen_random_uuid(), 'git', 'freeCodeCamp', 'Git and GitHub Full Course', 'https://www.youtube.com/watch?v=RGOj5yH7evk'),
    (gen_random_uuid(), 'data-structures', 'freeCodeCamp', 'Data Structures and Algorithms Full Course', 'https://www.youtube.com/watch?v=RBSGKlAvoiM'),
    (gen_random_uuid(), 'system-design', 'GitHub', 'System Design Primer', 'https://github.com/donnemartin/system-design-primer'),
    (gen_random_uuid(), 'design-patterns', 'Refactoring Guru', 'Design Patterns Catalog', 'https://refactoring.guru/design-patterns'),
    (gen_random_uuid(), 'oop', 'freeCodeCamp', 'Object Oriented Programming Explained', 'https://www.freecodecamp.org/news/object-oriented-programming-concepts-21bb035f7260/'),
    (gen_random_uuid(), 'agile', 'Atlassian', 'Agile Coach Tutorials', 'https://www.atlassian.com/agile'),
    (gen_random_uuid(), 'maven', 'Apache Maven', 'Maven in 5 Minutes', 'https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html'),
    (gen_random_uuid(), 'gradle', 'Gradle', 'Gradle Getting Started Tutorials', 'https://docs.gradle.org/current/userguide/getting_started_eng.html'),
    (gen_random_uuid(), 'postman', 'Postman', 'Postman Learning Center', 'https://learning.postman.com/'),
    (gen_random_uuid(), 'figma', 'Figma', 'Figma Learn - Free Design Tutorials', 'https://help.figma.com/hc/en-us/categories/360002051613'),
    (gen_random_uuid(), 'functional-programming', 'freeCodeCamp', 'Functional Programming Introduction', 'https://www.freecodecamp.org/news/functional-programming-in-javascript/'),
    (gen_random_uuid(), 'technical-writing', 'Google', 'Technical Writing Courses (free)', 'https://developers.google.com/tech-writing'),
    (gen_random_uuid(), 'code-review', 'Google', 'Engineering Practices - Code Review Guide', 'https://google.github.io/eng-practices/review/');
